name: Build package on PR
'on': pull_request
jobs:
  build_and_pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node@v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build app
        run: yarn build

      - name: Package app
        run: yarn package

      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          path: out/*
